### ISSUE TITLE
Mkdocs serve error - The "schema-reader" plugin is not installed

### ISSUE THREAD

**Issue by mjppires** [magicaljellybeans/mkdocs_schema_reader#1]
After installing the plugin using pip, when I run the command `mkdocs serve` I get the error below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/35525927/108325462-ff8ca900-71c0-11eb-87c3-a8527f323707.png)

Here are the version of python and mkdocs I'm using:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/35525927/108325525-0f0bf200-71c1-11eb-8dd7-08e8c1711f87.png)

And here is the configuration added in the mkdocs.yml:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/35525927/108325740-51353380-71c1-11eb-8b32-cb275e0582ac.png)

**Expected behavior:**
Convert schema files into markdown files

**Actual behavior:**
Error on mkdocs serve

**Comment by perclausen** [comment]
@mjppires Did you by any chance find a solution for this issue?

**Comment by SandoDev** [comment]
Has anyone been able to run this project successfully?
do you have an example of how to do it?
here is another one but it doesn't work for me either :( https://pypi.org/project/MkDocsJsonSchemaPlugin/

**Comment by mjppires** [comment]
@perclausen  I couldn't find any solution, so I've included a link to the schema file and the users can download it and open it in another tool...

**Comment by goddard82** [comment]
I thought this was something I was doing wrong but now it seems this is a common issue.

**Comment by magicaljellybeans** [comment]
Hi, seems like I'm the only one getting this to run correctly.

Are those having problems able to check that the issue is not a mismatch between the python version that `mkdocs --version` and `pip3 --version` are pointing to? 

As in this issue here: https://github.com/mkdocs/mkdocs/issues/1836

**Comment by magicaljellybeans** [comment]
🤦 
I have corrected the documentation with regards to this issue.
Syntax is:
```
plugins:
  - search
  - schema_reader:
      include: 
        - "../JSONSchema/"
        - "../example/directory/schema.json"
```
As in `schema_reader` not `schema-reader`.

Please let me know if this fixes.

**Comment by goddard82** [comment]
@magicaljellybeans Underscore rather than hyphen works - thank you kindly 🙂

**Comment by magicaljellybeans** [comment]
Good, glad it works now. Note to self to get documentation correct the first time round.
